version: '2'
services:
  postgres:
    container_name: postgres-reserva
    image: ricardojob/db-reserva
    build: ./postgres
    ports:
     - "5435:5432"
    expose:
     - 5434  
    volumes:
     - postgres-volume-reserva:/var/lib/postgresql/data/
  web:
    container_name: app-reserva
    build: .
    image: ricardojob/reserva
    ports:
     - "8085:8080"
    links:
     - "postgres:banco"
networks:
  default:
    external:
      name: reserva
volumes:
    postgres-volume-reserva:
      driver: local